apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.store.id }}-pvc
  namespace: {{ .Values.store.namespace }}
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
  {{- if .Values.db.persistence.storageClass }}
  storageClassName: {{ .Values.db.persistence.storageClass }}
  {{- end }}
