apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.store.id }}-secrets
  namespace: {{ .Values.store.namespace }}
type: Opaque
data:
  db-password: {{ .Values.db.password | b64enc | quote }}
  db-root-password: {{ .Values.db.rootPassword | b64enc | quote }}
