apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.store.id }}
  namespace: {{ .Values.store.namespace }}
  labels:
    app: {{ .Values.store.id }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.store.id }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ if eq .Values.engine.type "woocommerce" }}80{{ else }}9000{{ end }}
      protocol: TCP
