apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-ingress
  namespace: {{ .Values.store.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.domain.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: store-app
                port:
                  number: 80
