apiVersion: v1
kind: Secret
metadata:
  name: store-secrets
  namespace: {{ .Values.store.namespace }}
type: Opaque
stringData:
  db-password: {{ .Values.db.password | quote }}
  db-root-password: {{ .Values.db.rootPassword | quote }}
