resources:
  requests:
    cpu: "50m"
    memory: "256Mi"
  limits:
    cpu: "250m"
    memory: "512Mi"

db:
  persistence:
    storageClass: standard # Kind default
    size: 500Mi

app:
  imagePullPolicy: IfNotPresent
